name: Nuclei

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://andersonbosa.github.io/

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: nuclei.sarif
          
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: nuclei.sarif
          path: nuclei.sarif
