name: TruffleHog Secrets Scan

on:
  # Scan changed files in PRs (diff-aware scanning):
  # pull_request: {}
  # Scan mainline branches and report all findings:
  # push:
  #   branches: ["main"]
  # Allows you to start manually
  workflow_dispatch: {}

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
